apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-demo
spec:
  selector: 
    matchLabels:
      app: pod-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: pod-demo
    spec:
      containers:
      - name: pod-demo
        image: phx.ocir.io/oraclemetodista/demo:latest
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"
        ports: 
        - containerPort: 8080
        - containerPort: 443
      imagePullSecrets:
        - name:  ocir-key
---

apiVersion: v1
kind: Service
metadata:
  name: service-demo
spec:
  selector:
    app: pod-demo
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
  type: LoadBalancer
